### ISSUE TITLE
Confusing configuration setup

### ISSUE THREAD

**Issue by bidah** [neopoly/facebook_canvas#1]
The last headline is hard to get what to do and how to do it.

**In your Rails application you can set the server name in which the application runs for Facebook canvas. The default value is set to: /.fb./**

What server name? the name facebook gives to your app? Why there is this regex? Also  the line `FacebookCanvas.server_name = /SERVERNAME/` where does it goes? in an initializer?

Seems like a great gem but I just got stucked with this setup. any feedback would be great.

thanks

**Comment by JanOwiesniak** [comment]
`FacebookCanvas.server_name` is a regular expression that matches the url to your _Secure Canvas URL_.

Let us assume the _Facebook Canvas_ has following _Secure Canvas URL_:

`https://my-project.neopoly.com/`

Then the configuration would probably look like this:

`FacebookCanvas.server_name = /my-project.neopoly.com/`

And yes you are right, you can put this code into a _initializer_.

The default is set to `/.fb./` because our secure canvas app urls always looks like this:

`https://my-project.fb.neopoly.com/`

So  `/.fb./` basically matches all our applications without any configuration through a initializer.

Hope thats helps.

**Comment by splattael** [comment]
@bidah 

Set `FacebookCanvas.server_name = /.*/` to match _any_ server name.

@Khalasar @JanOwiesniak May `/.*/` should be the default. WDYT?

**Comment by JanOwiesniak** [comment]
@splattael if we do this, every request, even Facebook unrelated stuff would be processed and maybe manipulated by this middleware. I'm not sure. Other opinions?

**Comment by bidah** [comment]
Thank you guys. I will try it out now.

**Comment by JanOwiesniak** [comment]
You should try out 0.2.0

https://github.com/neopoly/facebook_canvas/commit/89f755b39ac9b6d71fb0d4ebe08b44eab8e6a9fd

**Comment by splattael** [comment]
Closing this issue.

@bidah Feel free to re-open this issue to clarify configuration difficulties :)
